"""nullable user_id in recipes

Revision ID: 694954a7db9f
Revises: 7e9e705abb6b
Create Date: 2024-08-14 23:31:45.094099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694954a7db9f'
down_revision = '7e9e705abb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
